# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CDBOL' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'IQKeyboardManager'
  pod 'NVActivityIndicatorView'
  pod 'InputMask'
  pod 'JMMaskTextField-Swift'
  pod 'Cosmos', '~> 16.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
  pod 'FBSDKLoginKit'
  pod 'FBSDKLoginKit'
  pod 'SDWebImage', '~> 4.0'
  pod 'Alamofire'

  # Pods for CDBOL

  target 'CDBOLTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
